### ISSUE TITLE
`connection refused` spit by caddy with the example configuration

### ISSUE THREAD

**Issue by TGRush** [unmojang/drasl#60]
Hey there!

I've recently found this project and wanted to try self-hosting it. I've followed the instructions in installation.md and configuration.md to get the sample docker-caddy configuration. I'm running this all over Tailscale. My files currently look like this:

`docker-compose.yml`
```
version: "3"

services:
  caddy:
    image: docker.io/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
  drasl:
    image: docker.io/unmojang/drasl
    ports:
      - "25585:25585"
    volumes:
      - ./config:/etc/drasl
      - ./data:/var/lib/drasl
```

`Caddyfile`
```
# Should be the same as `Domain` in Drasl's config.toml
http://epic-server.faun-scala.ts.net

reverse_proxy :25585
```
> (I have added http:// in front to disable automatic HTTPs as it does not play nice with my Tailscale config at the moment)

`config.toml`
```
# Drasl default config file

# Example: drasl.example.com
Domain = "epic-server.faun-scala.ts.net"

# Example: https://drasl.example.com
BaseURL = "http://epic-server.faun-scala.ts.net"

ListenAddress = "127.0.0.1:25585"

# List of usernames who automatically become admins of the Drasl instance
DefaultAdmins = ["cyrus"]

[RegistrationNewPlayer]
Allow = true
AllowChoosingUUID = true
RequireInvite = true

```

However, when I run `docker compose up` and look at the log, `Caddy` returns an empty page because of the following error:
```json
{"level":"error","ts":1713493140.6753414,"logger":"http.log.error","msg":"dial tcp 127.0.0.1:25585: connect: connection refused","request":{"remote_ip":"172.22.0.1","remote_port":"45926","client_ip":"172.22.0.1","proto":"HTTP/1.1","method":"GET","host":"epic-server.faun-scala.ts.net","uri":"/","headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate"],"Connection":["keep-alive"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0"],"Sec-Gpc":["1"],"Upgrade-Insecure-Requests":["1"],"Accept-Language":["en-US,en;q=0.5"],"Dnt":["1"]}},"duration":0.000841842,"status":502,"err_id":"q1a5zcsr1","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
```

I cannot for the life of me get Drasl to not refuse the connection from Caddy, and would like some help figuring out *what the hell is going on* as someone which only recently dabbled in hosting things like `Caddy`
