### ISSUE TITLE
Document how to use with Minecraft Console Client

### ISSUE THREAD

**Issue by TechClusterHQ** [unmojang/drasl#66]
Since [PR #2611](https://github.com/MCCTeam/Minecraft-Console-Client/pull/2611), MCC has support for adding custom yggdrasil servers.
Because one of the best uses of this server is creating more accounts for bots, I'd like to use my custom auth server with MCC.
Setting AccountType and AuthServer to the values results in a "Network Error" on the MCC side an a 404 on the Drasl side:

```
{"time":"2024-04-28T07:43:37.836718975Z","id":"","remote_ip":"xxxxx","host":"mca.xxxxx.com","method":"POST","uri":"/api/yggdrasil/authserver/authenticate","user_agent":"MCC/1.20.4","status":404,"error":"code=404, message=Not Found","latency":39509,"latency_human":"39.509µs","bytes_in":246,"bytes_out":50}
```

Configuration:
```toml
AccountType = "yggdrasil"                   # Account type: "mojang" OR "microsoft" OR "yggdrasil". Also affects interactive login in console.
Method = "mcc"                              # Microsoft Account sign-in method: "mcc" OR "browser". If the login always fails, please try to use the "browser" once.
AuthServer = { Host = "mca.xxxxx.com", Port = 443 } # Yggdrasil authlib server domain name and port.
```

Since you mentioned in the README that working with bots is a primary use case for this project it'd be great if usage with MCC could be documented or if you could let me know how.
